CREATE DATABASE IF NOT EXISTS companydb;

CREATE TABLE IF NOT EXISTS employee (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  salary INT(5) NOT NULL,
  PRIMARY KEY (id)
);

DESCRIBE employee;